#!/bin/bash
#
# Copyright (c) 1995-2015 Remsnet Consulting & Internet Services LTD
# Author:  Remsnet LTD Support <support at remsnet dot de>
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.
# Please submit bugfixes or comments via https://github.com/remsnet/mysql_ndb_cluster_helper


### BEGIN INIT INFO
# Provides:          mysql ndb ndbd
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:      3
# Default-Stop:     2 4 5
# Short-Description: Regular background program processing daemon
# Description:        mys2ql cluster
### END INIT INFO

PATH=$PATH:/usr/local/mysql

test -x /bin/bash || echo " $0 usage require /bin/bash "

function start_ndb_mgmd {
        #
        su - mysql -c 'cd /usr/local/mysql/mysql-cluster; /usr/local/mysql/mysql-cluster/start_mgmd.sh'
}

function start_mysqld {
        #
        su - mysql -c 'cd /usr/local/mysql/mysql-cluster; /usr/local/mysql/mysql-cluster/start_mysqld.sh'
}

function start_ndbd {
        #
        su - mysql -c 'cd /usr/local/mysql/mysql-cluster; /usr/local/mysql/mysql-cluster/start_ndbd.sh'
}


case "$1" in
start_mgmd)
        start_ndb_mgmd
        ;;
start_ndb)
        start_ndbd
        ;;
start_mysql)
        start_mysqld
        ;;
*)      echo "Usage: $0 {start_mgmd|start_ndb_4|start_ndb_5|start_mysql_5|start_mysql_5}"
        ;;
esac
exit 0
